### ISSUE TITLE
ng-block-ui error ivy enable angular 8

### ISSUE THREAD

**Issue by wkjesus** [kuuurt13/ng-block-ui#115]
i am actually testing a migrate project to angular 8.x, with ivy enable, and when run the server
on browsers console, i get this error: 

ng-block-ui: TypeError: Cannot read property 'localName' of null
    at ng-block-ui.js:878
    at Array.find (<anonymous>)
    at BlockUIDirective.push../node_modules/ng-block-ui/__ivy_ngcc__/fesm5/ng-block-ui.js.BlockUIDirective.findContentNode (ng-block-ui.js:878)
    at BlockUIDirective.push../node_modules/ng-block-ui/__ivy_ngcc__/fesm5/ng-block-ui.js.BlockUIDirective.ngOnInit (ng-block-ui.js:834)
    at callHook (core.js:2090)
    at callHooks (core.js:2060)
    at executeHooks (core.js:2017)
    at executePreOrderHooks (core.js:1991)
    at refreshDescendantViews (core.js:7581)
    at checkView (core.js:9015)

the version is  "ng-block-ui": "2.1.8".

**Comment by kuuurt13** [comment]
@wkjesus thanks for reporting. I will take a look and see what is going on here.

**Comment by kuuurt13** [comment]
@wkjesus I think I have fixed this issue and using the ivy renderer should now be supported. Can you please install the latest beta version and give it a shot.

`npm install ng-block-ui@next`

**Comment by wkjesus** [comment]
Thx for reply, but unfortunately, still have the same consolo error !  :(

i test on crhome, firefox and edge(chromium) and get same result. 
this is the component on package json: 

"dependencies": {
    "@angular/animations": "8.2.14",
    "@angular/cdk": "8.2.3",
    "@angular/common": "8.2.14",
    "@angular/compiler": "8.2.14",
    "@angular/core": "8.2.14",
    "@angular/forms": "8.2.14",
    "@angular/http": "7.2.15",
    "@angular/platform-browser": "8.2.14",
    "@angular/platform-browser-dynamic": "8.2.14",
    "@angular/router": "8.2.14",
    "@ng-select/ng-select": "3.7.1",
    "ag-grid-angular": "22.1.1",
    "ag-grid-community": "22.1.1",
    "angular-calendar": "0.28.2",
    "angular2-knob": "1.1.15",
    "angular2-text-mask": "9.0.0",
    "angular2-toaster": "8.0.0",
    "bootstrap": "4.4.1",
    "chart.js": "2.9.3",
    "core-js": "3.6.2",
    "date-fns": "2.8.1",
    "devicon": "2.2.0",
    "font-awesome": "4.7.0",
    "fullcalendar": "4.0.0-alpha",
    "moment": "2.24.0",
    "ng-block-ui": "^3.0.0-beta.3",
    "ng2-ace-editor": "0.3.9",
    "ng2-charts": "2.3.0",
    "ng2-file-upload": "1.4.0",
    "ng2-notifications": "0.3.0",
    "ngx-bootstrap": "5.2.0",
    "ngx-order-pipe": "2.0.4",
    "ngx-pagination": "5.0.0",
    "ngx-perfect-scrollbar": "8.0.0",
    "ngx-quill": "7.3.11",
    "node-sass": "^4.13.0",
    "primeicons": "2.0.0",
    "primeng": "8.1.1",
    "prismjs": "1.18.0",
    "quill": "1.3.7",
    "rxjs": "6.5.4",
    "rxjs-compat": "6.5.4",
    "simple-line-icons": "2.4.1",
    "sweetalert2": "9.5.4",
    "ts-helpers": "1.1.2",
    "zone.js": "0.10.2"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "0.803.21",
    "@angular/cli": "8.3.21",
    "@angular/compiler-cli": "8.2.14",
    "@angular/language-service": "8.2.14",
    "@angularclass/hmr": "2.1.3",
    "@types/jasmine": "3.5.0",
    "@types/jasminewd2": "2.0.8",
    "@types/node": "13.1.4",
    "codelyzer": "5.2.1",
    "husky": "^4.0.0",
    "jasmine-core": "3.5.0",
    "jasmine-spec-reporter": "4.2.1",
    "json-server": "^0.15.1",
    "jsonwebtoken": "^8.5.1",
    "karma": "4.4.1",
    "karma-chrome-launcher": "3.1.0",
    "karma-coverage-istanbul-reporter": "2.1.1",
    "karma-jasmine": "3.0.1",
    "karma-jasmine-html-reporter": "1.5.1",
    "minimist": "^1.2.0",
    "nodemon": "^2.0.2",
    "npm-run-all": "4.1.5",
    "pre-commit": "^1.2.2",
    "prettier": "^1.17.1",
    "pretty-quick": "^1.11.0",
    "protractor": "5.4.2",
    "ts-node": "8.5.4",
    "tslint": "^5.12.1",
    "tslint-config-prettier": "^1.18.0",
    "tslint-plugin-prettier": "^2.0.1",
    "typescript": "^3.5.3"
  },

ng-block-ui: TypeError: Cannot read property 'localName' of null
    at ng-block-ui.js:855
    at Array.find (<anonymous>)
    at BlockUIDirective.push../node_modules/ng-block-ui/__ivy_ngcc__/fesm5/ng-block-ui.js.BlockUIDirective.findContentNode (ng-block-ui.js:855)
    at BlockUIDirective.push../node_modules/ng-block-ui/__ivy_ngcc__/fesm5/ng-block-ui.js.BlockUIDirective.ngOnInit (ng-block-ui.js:811)
    at callHook (core.js:2090)
    at callHooks (core.js:2060)
    at executeHooks (core.js:2017)
    at executePreOrderHooks (core.js:1991)
    at refreshDescendantViews (core.js:7581)
    at checkView (core.js:9015)

**Comment by kuuurt13** [comment]
@wkjesus thanks for the details. Looking at your package json it shows that you have`"ng-block-ui": "^3.0.0-beta.3"` installed and not the latest version that I have published to fix the issue. Did you run the command in my previous comment (`npm install ng-block-ui@next`) because the latest version is `3.0.0-beta.4`?

**Comment by wkjesus** [comment]
Sure, i execute the command by the way, i think my proxy in the work, not download beta.4 ,  but
now i donwloaded manually, and i have to thanks.. the issue is gone, and have a functionally block-ui, on
ivy running, thx for your amazing time, and amazing plugin.

**Comment by kuuurt13** [comment]
Great, good to hear it is working! 👍
